language: java
jdk:
- openjdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod a+x ./gradlew
script:
- "./gradlew test"
deploy:
  provider: script
  script: "./gradlew publish"
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(master|develop)$"
    java: openjdk8
env:
  global:
  - secure: p+eOkTVxGjA6lSxZdw3ug/TfmGiCq4F/H/n5sUWswHF8LYdJvg/dvjrG4ldvbMJxIODQ2/GjgH6ZFkma4TXrL8zIqbq9ctD9cwNxeY2sgGMWmD5ti+zRBqEEWJqRjyIjXUFVfF8jE0z2CVTN/nzRRbXuk9y1FUE63D6epALJXajIaNGBdxuuV7a0tbz2+UQsxntQLD/Es/RJBqdlozUwb32y24hE2sQaESDPIY6Hfl6NyD7UobH84ajZpWgENEXETvBA6wYRnWDbYRUEX6V/azUoN1gO+7BmdykNjk3bOxmLTXTJmSmZ7tr/6jS1Hxn5TKaB2saMATZarNZRIXjWIvCAXog8fNysd8YASMTkFm+iSnfCYgp3uOXro1SEnnc2EFqN9p+zwONsDRBawZtsFCEp910jaBdfKsy9EZAcxevaBv4H4YGOelpOMVi6QHACtrwC/Wb1BwiJPP6WQ8ObCBMm+uNb0iC8fXriP+RJwdL79wq+M5LpfRB56KrpCOdTVPpHAN9YUXWj1H/RP/2R5uQxaIICwHFKIe+rVoWDwUjlc3EMuW7h0Hbl6N0JDhLld0ZwZEBL9tfSzKLRknBaEbZso6uQBwfhLtkNrASDMbnPBaYIAwmT83hwclfEwYYllyc2OlfHJtLFyQlHeQvinV3UbdJiclNpKkohbqaMeeM=
  - secure: zmOT8hISLzEFe0eVbt1uLDJPvk6wYMC4E2MpYFiVxI3njaTGxy0Sq4J4ExSbbXw6NxkYF5WotKv5iAd9Utab/jPiuLz8Ol/4U6kJ/X/W8xOixmHY9WdEJPAgtBVbcElvu+6fCy/NshDdpN3vPPaOQjLpyENreZOq7RPVkX6o9aBibTiwpNeZ6b19TCxSjlOJCDefcXy7uAqmkZsGrSmgkqCEkbj2bp5jglYTjCp8cKJqTHn5Nw6YKROglff4ltYtmH81OcuUmYMA4LMWtsBJs0W8/xmtsUVgweZ5EMzNe/wC14I/droo2hzLawhB6iI0ke4rSHQHuDQI53hUXn7mmK13JbomgU2yEGSJKPdfXT/A8jg3XlxX51xxR8rwCKKJWb5uJfYlO5ejV6gBctDDP0Hsrji8tSD/7f81aS/7jHvWAqtJMvn6nZJhG70ra9+uunLaqcx8EK47fTJlWb2yi2TIqaqnfZ+LzuEE+QScIp1jOP99N1B/a0c/WtppmAUGn1m+vhdEBZCWzietVC17uRKX1YFLCKtnDbAZknOi9Ilzd/IvrXhCmiGVlY/s8KyHsQjfAIL8f3e44JYJNY2ceiNjjqBU+YEWubvPq6QZP1H3szRt2niNYVGYD9S60q3P3rgwvT27MYRTsNXWXRR1V5PoWl5U7cic+5NjnJQVhU0=
