language: java
jdk:
- openjdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod a+x ./gradlew
script:
- ./gradlew test
deploy:
  provider: script
  script: travis_retry ./gradlew publish
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|develop)$
    java: openjdk8
env:
  global:
  - secure: JuCVrgIDGCr/KM/T4NLeO9BCNFp1cJTWIHlJ87sFOSno8Q7rcBQmqRnsPROCw/tmdB6Pp46DBByNslfYHrQxAQPHcII7O0YtIqnCh8Ij6z5GaHPoTu8MsK+3fBUUq0T1ZfJk/RqcVvBlcEfY4nf06n9DnuysYkXhJM+Se6J2jGkwtKDdBznjIBmOIU/Qb8XAlmVodi6hzuvfmMvVVvm4JWL8Qpw4j/TSGqZfX9p1ioEZllXLvM5ABxMrd26hEjeQK/5eZ0s3GOsPpsRIxUT4odX5q4kOUS3aI9Zr4LamjmX3LF3kNeMlkXfFXZkcGHm4xgoe98BSmbLQBWMzvcGL5VCL67YB6EJ/WieFvEtbeH+o4OjsEFM0RNapyeOooP6EpMhHW8f9pFwg95cG6ZhegFI7q09JgUYLxNHEsWSJe1+P1dNnkYThM65Iub5sj+otPTw2F4Sd5wNdrTK3J3XRbXlAoy/Ryre2LvvcN9V6IZ/tfrJmOcV4JVRfK3CVduUNktqHpPM/RuQKKPAWrsce8hdK1F/p8jKpOyjI2mzfyjT/q58VxB3qFWytjwbgtq7awBDM6TEHZcOVe9mokgTRLFQoTURt2vwp+LDBW0NScS721LQSK2p2s3MXVY71a5FyeWQ39Xa467o782got7IVzFP7hDJDrxvuV1fKycuqdEI=
  - secure: sLZoLPaI6py3N7JTG6ZmLH8IoLiDzonAOYq0M067Q4B6NblVb+zMnwiNj0TThPHa8dvE4IEpLFCuwzhCbdaf3Vje/iLpuRRMfA1TOwrtZWOmyNRCwIJGqdSZXna48VBftZBHUsY2tCUd290oFf+dhLt4XsHzwvI1l4VoyvscTHr+FFlNt1Ft0PSdMd40YRn2dX1PORaz9QLpQiBxpOllb2gc+fkrLpxNn1O/rlC4t7kYFk6uxCzX00e2N0rkCFylk8/KlUce945O1n2EU+uGzohbLa0RXRxo2ihhcrMqt+1YyFTHVvha+bQqITCpp3p3jB8ovu+36d/gvcD57Jz6H18a81vsuLY983XNOrhMb3pozjhbKX/KdfA/yi97RPNGHWjlxIOyAaGcxoMbF75Kvpt8oN2ZybmfrGmXDYk9nsfP1BNKhNKS0JYvNa7ur4swDQLLsYGdLzsdYfXGmMWzHZGnqSu4jbTJBv7piQ7z+u0tPTOOhpmDgGNS4/JuqedFT5XCN4qahAYW+iCzyWaqLxegaqWk8sxdpvcBLbFhyTbYx0jGBT9jR5lo7xOWCfNtyDTCM2mrBumt5l3pvkqvyQe5Gw2GHsFm2qsvU111S2s5jKyj9ZKEJK1UN3X4jITxJaSIhv7fvlHyQcqwCqMVlBu8EBBWXv116huJ35e4U74=
